nelmio_api_doc:
    areas:
        path_patterns:
            - ^/v
    models: { use_jms: false }
    documentation:
        info:
            title: Potato-API 🥔
            description: Yummy
            version: 1.0.0
        components:
            securitySchemes:
                ApiKeyAuth: # arbitrary name for the security scheme
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            -   ApiKeyAuth: []
