security:
    enable_authenticator_manager: true
    providers:
        user_provider:
            entity:
                class: App\Entity\UserAccount
                property: apiToken
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/|/doc|/doc.json$
            security: false
        main:
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
