services:
  http:
    container_name: potato-api-http
    image: nginx:stable-alpine
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - .:/var/www/potato-api
        - ./docker/http/site.conf:/etc/nginx/conf.d/site.conf
        - ./docker/http/snippets:/etc/nginx/conf.d/snippets
        - ./docker/http/certs:/etc/ssl/certs
    networks:
      static-network:
        ipv4_address: 172.1.128.1
  php:
    container_name: potato-api-php
    hostname: potato-api-php
    user: ${UID}:${GID}
    build:
        context: ./docker/php
        dockerfile: Dockerfile-php81
        args:
          - USER=$USER
          - UID=$UID
          - GID=$GID
    volumes:
        - .:/var/www/potato-api
        - ./docker/data/home/$USER:/home/$USER
        - "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK"
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    working_dir: /var/www
    environment:
        - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    networks:
      static-network:
        ipv4_address: 172.1.128.2
  db:
    container_name: potato-api-db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: potato-api
      POSTGRES_PASSWORD: potato-api
      POSTGRES_USER: potato-api
    volumes:
       - ./docker/data/db:/var/lib/postgresql/data:rw
    networks:
      static-network:
        ipv4_address: 172.1.128.3
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.1.0.0/16
